---
- name: Install required packages
  yum:
    name:
      - curl
      - policycoreutils-python
      - openssh-server
    state: latest

- name: Enable and start sshd
  service:
    name: sshd
    state: started
    enabled: yes

- name: Enable HTTP+HTTPS access
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - http
    - https

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: Install postfix
  yum:
    name: postfix
    state: latest

- name: Enable and start postfix
  service:
    name: postfix
    state: started
    enabled: yes

- name: Installation de npm
  yum:
    name:
      - npm
    state: latest

- name: Installation de nodejs
  yum:
    name:
      - nodejs
    state: latest

- name: Installation de redis
  yum:
    name: redis
    state: latest

- name: Activer redis
  service:
    name: redis
    state: started
    enabled: yes

- name: Actualiser node modules
  npm:
    path: /home/vagrant/userapi
    state: latest
